/* Housing */
export const SHOW_ALL_HOUSINGS = 'SHOW_ALL_HOUSINGS';
export const REMOVE_HOUSING = 'REMOVE_HOUSING';
export const ADD_HOUSING = 'ADD_HOUSING';
export const EDIT_HOUSING = 'EDIT_HOUSING';
export const SHOW_HOUSINGS_SUMMARY = 'SHOW_HOUSINGS_SUMMARY';

/* Auditoriums */
export const SHOW_AUDITORIUMS_OF_HOUSING = 'SHOW_AUDITORIUMS_OF_HOUSING';
export const EDIT_AUDITORIUM = 'EDIT_AUDITORIUM';
export const ADD_AUDITORIUM = 'ADD_AUDITORIUM';
export const REMOVE_AUDITORIUM = 'REMOVE_AUDITORIUM';
export const SHOW_AUDITORIUMS_SUMMARY = 'SHOW_AUDITORIUMS_SUMMARY';