/* Housing */
export const FETCH_HOUSINGS_START = 'FETCH_HOUSINGS_START';
export const FETCH_HOUSINGS_COMPLETE = 'FETCH_HOUSINGS_COMPLETE';
export const FECTH_HOUSINGS_INFO_START = 'FETCH_HOUSINGS_INFO_START';
export const FETCH_HOUSINGS_INFO_COMPLETE = 'FETCH_HOUSINGS_INFO_COMPLETE';
export const HOUSING_FORM_UPDATE = 'HOUSING_FORM_UPDATE';
export const HOUSING_FORM_ERROR_MESSAGE = 'HOUSING_FORM_ERROR_MESSAGE';
export const HOUSING_EDIT_FILL_FORM_START = 'HOUSING_EDIT_FILL_FORM_START';
export const HOUSING_EDIT_FILL_FORM_COMPLETE = 'HOUSING_EDIT_FILL_FORM_COMPLETE';
export const HOUSING_EDIT_START = 'HOUSING_EDIT_START';
export const HOUSING_EDIT_COMPLETE = 'HOUSING_EDIT_COMPLETE';
export const HOUSING_RESET_FORM = 'HOUSING_RESET_FORM';
export const REMOVE_HOUSING = 'REMOVE_HOUSING';
export const ADD_HOUSING = 'ADD_HOUSING';
export const EDIT_HOUSING = 'EDIT_HOUSING';

/* Auditoriums */
export const FETCH_AUDITORIUMS_START = 'FETCH_AUDITORIUMS_START';
export const FETCH_AUDITORIUMS_COMPLETE = 'FETCH_AUDITORIUMS_COMPLETE';
export const FETCH_AUDITORIUMS_INFO_START = 'FETCH_AUDITORIUMS_INFO_START';
export const FETCH_AUDITORIUMS_INFO_COMPLETE = 'FETCH_AUDITORIUMS_INFO_COMPLETE';
export const SHOW_AUDITORIUMS_OF_HOUSING = 'SHOW_AUDITORIUMS_OF_HOUSING';
export const EDIT_AUDITORIUM = 'EDIT_AUDITORIUM';
export const ADD_AUDITORIUM = 'ADD_AUDITORIUM';
export const REMOVE_AUDITORIUM = 'REMOVE_AUDITORIUM';